export const RETRIEVAL_FEATURE_VERSION = 1 as const;

export const MINIMUM_TRAINING_EXAMPLES = 30;
export const MINIMUM_DISTINCT_QUERIES = 10;
export const VALIDATION_FRACTION = 0.2;

export const TRAINING_LEARNING_RATE = 0.01;
export const TRAINING_L2_REGULARIZATION = 0.1;
export const TRAINING_MAX_EPOCHS = 2_000;
export const TRAINING_EARLY_STOPPING_PATIENCE = 50;
export const TRAINING_LOSS_TOLERANCE = 1e-8;
