name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pylint
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
    - name: Analysing the code with pylint
      run: |
        python -m pylint --errors-only --disable=import-error app api core config.py tests/test_*.py sandbox/session_debug/*.py
